### ISSUE TITLE
As a Juta Shoes Maker, I can log a new craft and view my previously logged crafts

### ISSUE THREAD

**Issue by tdoran** [fac-13/craft-track#1]
User Stories associated:

- [x] As a Juta Shoes Maker, I can open the app and choose to try it out - issue #2
- [x] As a Juta Shoes Maker, I can log a new craft - issue #3
- [x] As a Juta Shoes Maker, I can view my newly-added craft and previously logged crafts - issue #4
