### ISSUE TITLE
As a Juta Shoes Maker, I can log a new craft

### ISSUE THREAD

**Issue by tdoran** [fac-13/craft-track#3]
- [x] Create button to open form component - issue #7
- [x] Create form component for logging new craft - issue #8
- [x] Create form saving functionality - issue #9
- [x] On <Form> press the 'X' icon to return to all products - issue #28
