### ISSUE TITLE
As a Juta Shoes Maker, I can view my newly-added craft and previously logged crafts

### ISSUE THREAD

**Issue by tdoran** [fac-13/craft-track#4]
- [x] Create All Crafts component - issue #10 
- [x] Implement DynamoDB form submission + Data retrieval - issue #40
- [x] Connect Client and Server sides via API request - issue #47  
- [x] Render All.js component based on DynamoDB response - issue #46
