### ISSUE TITLE
As a maker, I can toggle between to do and done products

### ISSUE THREAD

**Issue by helenzhou6** [fac-13/craft-track#49]
User stories for the 'To Do' page:
- [x] I can add an order to the list, on the to do page - issue #50 
- [x] I can view all the orders to be done - issue #51
- [x] I can mark and view what steps I have completed for all orders (sewn/cut) - issue #52
- [ ] I can remove or edit an order - issue #53
- [ ] I can click on the button 'Add to Completed' and select specific orders - issue #54
- [ ] I can see these order(s) have been moved to the Completed page - issue #55

User stories for the 'Completed orders to be invoiced' page:
- [ ] I can view all the orders that I have completed, but not yet invoices  - issue #56
- [ ] I can revert an order back to the to do page  - issue #57
- [ ] I can select which orders to use to make an invoice  - issue #58 
- [ ] I can click on the 'make invoice' button (and be informed that it will remove these items?)  - issue #59
